CREATE TABLE IF NOT EXISTS tasks (
    task_id INTEGER PRIMARY KEY ,
    title TEXT NOT NULL,
    description TEXT,
    completed BOOLEAN NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    completed_at  DATETIME
);